import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const sourceDir = path.dirname(fileURLToPath(import.meta.url));
const deckDir = path.dirname(sourceDir);
const outDir = process.env.MWENDO_DECK_OUTPUT_DIR || path.join(deckDir, 'build-output');
await fs.mkdir(outDir,{recursive:true});
const W=1280,H=720, navy='#17365D', ink='#102A43', blue='#2F75B5', teal='#00A6A6', pale='#F5F8FC', line='#D8E2EE', amber='#F6C85F', red='#C94C4C', white='#FFFFFF', gray='#52606D';
const p=Presentation.create({slideSize:{width:W,height:H}});
function box(slide,x,y,w,h,fill='none',stroke='none',radius='rounded-lg'){const o={geometry:radius==='none'?'rect':'roundRect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:stroke,width:stroke==='none'?0:1}};if(radius!=='none')o.borderRadius=radius;return slide.shapes.add(o);}
function txt(slide,text,x,y,w,h,size=20,color=ink,bold=false,align='left'){const s=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});s.text=text;s.text.style={fontSize:size,color,bold,align,verticalAlignment:'mid'};return s;}
function title(slide,kicker,heading,sub=''){txt(slide,kicker.toUpperCase(),72,38,500,22,13,blue,true);txt(slide,heading,72,70,1120,58,36,ink,true);if(sub)txt(slide,sub,72,132,1120,38,18,gray,false);}
function footer(slide,source='Sources: Strategic Partnership Memorandum; SPV Financial Term Sheet; illustrative workbook outputs'){txt(slide,source,72,686,1120,18,10,gray,false);}
function pill(slide,text,x,y,w,fill=blue,color=white){box(slide,x,y,w,30,fill,'none','rounded-full');txt(slide,text,x,y+2,w,24,13,color,true,'center');}
function card(slide,head,body,x,y,w,h,accent=blue){box(slide,x,y,w,h,white,line);box(slide,x,y,6,h,accent,'none','none');txt(slide,head,x+22,y+16,w-40,28,20,ink,true);txt(slide,body,x+22,y+52,w-40,h-64,16,gray,false);}
function flow(slide,labels,y,colors){const gap=18, w=(1120-(labels.length-1)*gap)/labels.length;labels.forEach((l,i)=>{const fill=colors?.[i]||white;const tc=(fill===white||fill===pale)?ink:white;box(slide,72+i*(w+gap),y,w,70,fill,line);txt(slide,l,84+i*(w+gap),y+14,w-24,42,16,tc,true,'center');if(i<labels.length-1)txt(slide,'→',72+(i+1)*w+i*gap+2,y+20,gap-4,28,22,blue,true,'center');});}

// 1
{const s=p.slides.add();s.background.fill=navy;txt(s,'MWENDO PAMOJA',72,72,500,28,16,'#9CC7E8',true);txt(s,'Financing resilient\ngig-economy cash flows',72,150,760,170,52,white,true);txt(s,'$9m SPV facility | Phase 1 pilot | Lender and DFI investment case',76,356,760,36,22,'#D9EAF7');pill(s,'Illustrative underwriting case',76,432,250,teal);txt(s,'20 AUGUST 2026',72,650,300,18,12,'#9CC7E8',true);txt(s,'01',1130,650,70,26,18,white,true,'right');}
// 2
{const s=p.slides.add();title(s,'Investment question','Can a ring-fenced SPV turn volatile driver cash flows into financeable receivables?','The underwriting thesis is a cash-flow stabilization proposition, not a conventional retail-credit score.');card(s,'The asset','A driver is a concentrated operating asset: vehicle, platform access, insurance and wallet liquidity are interdependent.',72,220,340,210,blue);card(s,'The risk','A fuel, health, platform or income shock can cascade across products and create correlated defaults.',470,220,340,210,red);card(s,'The proposition','Observe liquidity continuously, intervene early, and protect collections through subordination, OC, reserve and waterfall controls.',868,220,340,210,teal);footer(s);}
// 3
{const s=p.slides.add();title(s,'Risk mechanics','One shock can become a multi-product default cascade');flow(s,['External shock','Cash-flow\nsuffocation','Arrears','Insurance\nlapse','Platform\ndeactivation','Multi-product\ndefault'],250,[red,'#FBE5E5','#FFF2CC','#FFF2CC','#FBE5E5',red]);card(s,'Why correlation matters','IPF, microloans and revolving credit draw on the same wallet and operating asset. Tail dependence is therefore a portfolio feature, not an edge case.',200,410,880,110,red);footer(s);}
// 4
{const s=p.slides.add();title(s,'Intervention thesis','Move from score-and-collect to observe-and-stabilize');flow(s,['Observe','Detect','Price','Intervene','Stabilize cash flow','Protect collections'],245,[blue,blue,teal,teal,'#3B8C66','#3B8C66']);txt(s,'Continuous underwriting turns explicit liquidity signals into timely actions before arrears harden.',240,400,800,42,24,ink,true,'center');pill(s,'Early action is a credit enhancement',435,492,410,navy);footer(s);}
// 5
{const s=p.slides.add();title(s,'Counterparty ecosystem','Each party has a defined economic role');const nodes=[['Driver',100,220,blue],['Platform',350,220,teal],['HoldCo / OpCo',600,160,navy],['Carrier',600,280,blue],['SPV',850,220,navy],['Class A / B',1080,160,red],['Class C',1080,280,teal]];nodes.forEach(([t,x,y,c])=>{box(s,x,y,150,66,c,'none');txt(s,t,x+10,y+18,130,30,17,white,true,'center');});txt(s,'→',274,236,60,30,28,blue,true,'center');txt(s,'→',524,236,60,30,28,blue,true,'center');txt(s,'→',774,236,60,30,28,blue,true,'center');txt(s,'→',1004,176,60,30,28,blue,true,'center');txt(s,'→',1004,296,60,30,28,blue,true,'center');txt(s,'IP, servicing, data and interventions',600,410,400,28,17,gray,true,'center');footer(s);}
// 6
{const s=p.slides.add();title(s,'Ring-fencing','Separate operating-company risk from receivable cash flows');card(s,'HoldCo / OpCo','Owns IP, engineering, regulatory work, API integrations and operating infrastructure. The $1m venture-debt overlay stays here.',72,220,500,180,navy);card(s,'SPV','Owns purchased receivables and their collections. Senior and mezzanine lenders claim the SPV waterfall.',708,220,500,180,teal);flow(s,['True-sale diligence','Eligible receivables','SPV waterfall','Debt service'],230,470,[amber,blue,navy,red]);footer(s,'Sources: Strategic Partnership Memorandum; SPV Financial Term Sheet; implementation plan.');}
// 7
{const s=p.slides.add();title(s,'Capital stack','$9m SPV capitalization gives senior lenders structural protection');const vals=[['Class A','$6.75m','75%',red],['Class B','$1.35m','15%',amber],['Class C','$0.90m','10%',teal]];vals.forEach((v,i)=>{const y=225+i*105;box(s,130,y,700-i*180,66,v[3],'none');txt(s,v[0],150,y+18,160,26,20,white,true);txt(s,v[1],420,y+18,180,26,22,white,true,'right');txt(s,v[2],620,y+18,150,26,18,white,true,'right');});card(s,'Priority','Class A receives interest and principal before mezzanine and first-loss equity. Equity distributions are blocked when controls fail.',870,235,320,180,blue);footer(s);}
// 8
{const s=p.slides.add();title(s,'Collateral and coverage','Advance rate and OC conventions are explicit');const metrics=[['$9.0m','SPV capitalization'],['75%','advance rate'],['$12.0m','implied eligible receivables'],['148.1%','base OC vs 125% target'],['3 months','CRA requirement']];metrics.forEach((m,i)=>{const x=72+i*224;box(s,x,235,204,118,pale,line);txt(s,m[0],x+12,256,180,36,28,navy,true,'center');txt(s,m[1],x+12,302,180,28,14,gray,false,'center');});txt(s,'Base convention: Eligible Receivables = Total SPV Capital / Advance Rate; OC = Eligible Receivables / (Class A + Class B).',150,430,980,44,18,gray,false,'center');footer(s);}
// 9
{const s=p.slides.add();title(s,'Asset pool','Three products, one cash-flow engine');const ps=[['IPF','Premium financed; policy term, grace, cancellation and recovery lag.',blue],['Microloan','Fare-linked instalments; arrears, restructuring and sufficiency controls.',teal],['Revolver','Limit, utilization, repayments and draw-freeze logic.',navy]];ps.forEach((p0,i)=>card(s,p0[0],p0[1],72+i*386,230,350,160,p0[2]));txt(s,'Cohort schedules track origination, collections, defaults, recoveries and closing balances by product and month.',180,455,920,35,20,ink,true,'center');footer(s);}
// 10
{const s=p.slides.add();title(s,'Clarified underwriting architecture','Explicit liquidity is a named feature path, not a policy shortcut');flow(s,['Raw telematics\nand wallet events','Flink feature\nservices','GRU / Transformer\nneural embeddings','Explicit Liquidity\nFeature Path','Bayesian\nunderwriting','Policy +\nCompliance Gate'],210,[white,blue,navy,teal,blue,red]);txt(s,'CFA • DLR • Earnings Velocity • Repayment Velocity • Wallet Volatility • Reserve Balance • Time Since Depletion',145,380,990,34,16,teal,true,'center');pill(s,'Canonical terminology replaces the ambiguous legacy label',345,465,590,navy);footer(s);}
// 11
{const s=p.slides.add();title(s,'Decision stack','Bayesian inference produces risk; policy controls produce the operational decision');flow(s,['Neural representation\n+ Explicit liquidity features','Posterior PD\n+ credible interval','Credit Policy and\nCompliance Gate','Approve / reduce / freeze /\nrestructure / intervene'],230,[blue,teal,red,navy]);card(s,'Ownership rule','CFA, DLR and Earnings Velocity bypass the GRU and Transformer encoders and enter the Bayesian layer directly through spline and interaction terms.',220,405,840,112,teal);footer(s);}
// 12
{const s=p.slides.add();title(s,'Cash waterfall','Cash is allocated in a defined order, with equity last');const steps=['Statutory / trustee','Servicing fees','Class A interest','Class A principal','Class B interest','Class B principal','Reserve cure','Senior sweep','Class B sweep','Class C residual'];steps.forEach((t,i)=>{const x=74+(i%5)*232,y=220+Math.floor(i/5)*120;box(s,x,y,210,72,i<4?red:i<7?amber:teal,'none');txt(s,`${i+1}. ${t}`,x+10,y+22,190,28,15,white,true,'center');});txt(s,'Equity distributions stop when interest, principal, CRA, OC or early-amortization controls fail.',180,490,920,34,20,ink,true,'center');footer(s);}
// 13
{const s=p.slides.add();title(s,'Structural credit enhancement','Protection is layered before returns are distributed');const layers=[['First-loss equity','$0.90m',teal],['Overcollateralisation','148.1% base',blue],['Cash reserve','3 months debt service',navy],['Recoveries','40% illustrative net',amber],['Cash sweep','Early amortization',red]];layers.forEach((v,i)=>{const w=220+i*40;const x=72+(1120-w)/2;const y=190+i*74;box(s,x,y,w,54,v[2],'none');txt(s,`${v[0]}  |  ${v[1]}`,x+10,y+15,w-20,24,16,white,true,'center');});footer(s);}
// 14
{const s=p.slides.add();title(s,'Covenants and triggers','Hard-coded controls remain downstream of the model');const c=[['PSI ≥ 0.25','Freeze and recalibrate',amber],['NPL ≥ 6.5%','Early amortization',red],['Platform > 25%','Restrict purchases',blue],['Geo > 15%','Restrict purchases',blue],['OC < 125% / CRA shortfall','Cure and block equity',navy]];c.forEach((v,i)=>card(s,v[0],v[1],72+(i%3)*386,210+Math.floor(i/3)*170,350,125,v[2]));footer(s);}
// 15
{const s=p.slides.add();title(s,'Scenario stress','The deck will only claim protection the workbook calculates');const rows=[['Base Case','3.2% / 4.5%','No trigger','Base'],['Mild Shock','6.8% / 9.1%','Tighter limits','Stress'],['Severe Contagion','14.5% / 22.0%','Cash sweep / early amortization','Tail']];rows.forEach((r,i)=>{const y=220+i*100;box(s,100,y,1080,72,i===0?'#E5F3EC':i===1?'#FFF2CC':'#FBE5E5',line);txt(s,r[0],125,y+20,220,28,18,ink,true);txt(s,r[1],390,y+20,220,28,18,ink,true,'center');txt(s,r[2],650,y+20,300,28,17,gray,false,'center');txt(s,r[3],1020,y+20,120,28,15,blue,true,'center');});txt(s,'Senior principal protection is an output, not an unsupported promise.',250,535,780,32,21,red,true,'center');footer(s);}
// 16
{const s=p.slides.add();title(s,'Investor returns','Priority, not headline yield, is the core lender proposition');card(s,'Class A','T-Bill + 200 bps\nSenior interest and principal priority\nLowest structural loss exposure',72,220,350,200,red);card(s,'Class B','18%–22% target range\nSubordinated to Class A\nMezzanine compensation for risk',465,220,350,200,amber);card(s,'Class C','Residual return\nFirst-loss position\nDistributions blocked when controls fail',858,220,350,200,teal);pill(s,'Returns tie to waterfall, DSCR and scenario outputs',360,490,560,navy);footer(s);}
// 17
{const s=p.slides.add();title(s,'Diligence requirements','Replace illustrative assumptions before final credit approval');const items=['Historical portfolio tape by product and vintage','Executed platform, carrier and servicing agreements','Legal true-sale and bankruptcy-remoteness opinion','Collections, recoveries and loss-mitigation evidence','Model validation, fairness audit and data-quality controls','Reserve, hedge, tax and cash-management documentation'];items.forEach((t,i)=>{const y=190+i*58;txt(s,'✓',100,y,28,28,22,teal,true);txt(s,t,145,y,930,28,18,ink,false);});box(s,930,200,250,250,pale,line);txt(s,'Decision gate',955,225,200,28,21,navy,true,'center');txt(s,'Data room\n→ legal\n→ validation\n→ structuring',955,285,200,120,22,blue,true,'center');footer(s);}
// 18
{const s=p.slides.add();s.background.fill=navy;txt(s,'INVESTMENT COMMITTEE DECISION',72,74,700,22,14,'#9CC7E8',true);txt(s,'Approve the next diligence gate',72,130,900,58,42,white,true);txt(s,'Proceed to data-room diligence, legal true-sale work, model validation, and final facility structuring.',76,220,850,64,24,'#D9EAF7');flow(s,['Diligence','Legal','Validation','Structuring'],360,[teal,blue,blue,red]);pill(s,'$9m SPV | $1m HoldCo overlay | 36-month illustrative case',260,515,760,teal);txt(s,'18',1130,650,70,26,18,white,true,'right');}

const montage = await p.export({format:'webp',montage:true,scale:1}); await fs.writeFile(`${outDir}/Mwendo_Pamoja_Lender_Deck_montage.webp`,new Uint8Array(await montage.arrayBuffer()));
for (const [i,s] of p.slides.items.entries()) { const png=await p.export({slide:s,format:'png',scale:1}); await fs.writeFile(`${outDir}/deck-slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer())); }
const pptx=await PresentationFile.exportPptx(p); await pptx.save(`${outDir}/Mwendo_Pamoja_Lender_Presentation.pptx`); console.log('saved deck'); process.exit(0);
